# @see https://console.cloud.google.com/security/secret-manager?project=cryprobot
configurations:
  secret_keyname: 'EXCHANGE_SECRET'
  api_keyname: 'EXCHANGE_APIKEY'
  trade_with: 'USDT' # USDC | USDT
  rebalance:
    - 'BTC:40'
    - 'ETH:35'
    - 'BNB:15'
    - 'LINK:5'
    - 'ADA:10'
  trading_pairs:
    - 'BTC:USDT'
    - 'ETH:BTC'
    - 'BNB:BTC'
    - 'LINK:BTC'
    - 'ADA:BTC'
