configurations:
  secret_keyname: 'EXCHANGE_KRAKEN_SECRET'
  api_keyname: 'EXCHANGE_KRAKEN_APIKEY'
  trade_with: 'USDT'
  rebalance:
    - 'BTC:40'
    - 'ETH:35'
    - 'BNB:25'
  trading_pairs:
    - 'BTC:USDT'
    - 'ETH:BTC'
    - 'BNB:BTC'
