configurations:
  secret_keyname: 'EXCHANGE_BITFLYER_SECRET'
  api_keyname: 'EXCHANGE_BITFLYER_APIKEY'
  trade_with: 'JPY'
  rebalance:
    - 'BTC:70'
    - 'ETH:25'
    - 'XRP:5'
  trading_pairs:
    - 'BTC:JPY'
    - 'ETH:JPY'
    - 'XRP:JPY'
