version: '3.9'

services:

  dev:
    container_name: cryptobot_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:debug
    ports:
      - 3005:3005
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    tty: true
    environment:
      - NODE_ENV=development
      - PORT=3005
      - GUARD=none
      - EXCHANGE_NAME=binance
      - EXCHANGE_CONFIGFILE=config.binance.yaml

networks:
  nesjs-network: