name: push
on: 
  push:
    branches: 
      - main

env: 
  NODE_ENV: dev

jobs:
  test:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      # -- Copy code from the repository
      - name: Copy repository
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci
      
      - name: Lint code (ESLint & Prettier) 
        run: |-
          yarn lint
          yarn format

  deploy:
    name: Publish, and Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      # @see https://github.com/BricePissard/cryptobot/settings/secrets/actions
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/cryptobot
          git pull origin main
          yarn install --production
          yarn start:prod