name: push
on: 
  push:
    branches: 
      - main

jobs:
  test:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      # -- Copy code from the repository
      - name: Copy repository
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci
      
      - name: Lint code (ESLint & Prettier) 
        run: |-
          yarn lint
          yarn format

  deploy:
    name: Publish, and Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      # @see https://github.com/appleboy/ssh-action
      # @see https://github.com/BricePissard/cryptobot/settings/secrets/actions
      # bgsfTTyiwj8%$#vhiO90!!!jVodpgpowe%WWepkfa
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/cryptobot
          echo '${{ secrets.SSH_PASSWORD }}' | sudo fuser -k 3005/tcp
          echo '${{ secrets.SSH_PASSWORD }}' | sudo rm *.lock
          git pull origin main
          echo '${{ secrets.SSH_PASSWORD }}' | rm -rf 
          echo '${{ secrets.SSH_PASSWORD }}' | install --production
          cp src/services/configs/*.yaml dist/services/configs/
          echo '${{ secrets.SSH_PASSWORD }}' | yarn start:prod &